// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PauseMusic():Promise<void>;

export function PlayMusic():Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
