name: "🚀 Feature Request"
description: Suggest a new feature to improve OpenTurntable
labels: ["enhancement", "pending review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make this feature request!

        Please review currently open issues first to ensure that this feature hasn't been suggested yet:
        https://github.com/TheRandomMelon/OpenTurntable/issues
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a good addition to OpenTurntable, including possible use cases. If you have a working prototype that implements this feature, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Final questions
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
          required: false
        - label: Did you check existing [issues](https://github.com/TheRandomMelon/OpenTurntable/issues) to see if this feature has already been implemented?
          required: true
